name = "study-api"
main = "src/worker.js"
compatibility_date = "2023-12-01"

# Pages 配置
pages_build_output_dir = "dist"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "study-database"
database_id = "e94c1e60-35eb-4a42-91ae-cdbe6394cb73"

# 环境变量
[vars]
AUTH_TOKEN = "123456"

# CORS 设置
[env.production]
name = "study-api"

[env.production.vars]
AUTH_TOKEN = "123456"