name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # 或你项目使用的分支名

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets._d0Tp9oDM3qQs8I5ohZESYy3kBzXNZasvjEZ-nm2 }}
          accountId: ${{ 7b1b0296a3539efed3feeb0fa5a3de29 }}
          projectName: studyweb  # 你的 Cloudflare Pages 项目名
          directory: dist
